[package]
name = "function-macro"
version = "0.1.0"
edition = "2021"

[lib]
name = "my_macro"
path = "src/lib.rs"
proc-macro = true

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.29", features = ["parsing"] }
