[package]
name = "sorted-macro"
version = "0.1.0"
edition = "2021"

[lib]
name = "sorted_macro"
path = "src/lib.rs"
proc-macro = true

[[test]]
name = "tests"
path = "tests/test-1.rs"

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.29", features = ["parsing"] }
